#!/bin/sh

# ---------------------------------------------------------------------------
# jcha - Java Class Histogram Analyser
#        start script
# ---------------------------------------------------------------------------

if test -z $JCHA_CP; then
	JCHA_CP=`dirname "$0"`/target/jcha-1.0-SNAPSHOT.jar
fi

# -- JavaFX is not in the standard runtime path for Java 7 => add it  
JCHA_CP=${JCHA_CP}:${JAVA_HOME}/jre/lib/jfxrt.jar

java -cp ${JCHA_CP} com/trivago/jcha/apps.App $*

