#!/bin/sh

# ---------------------------------------------------------------------------
# jcha - Java Class Histogram Analyser
#        start script

#######################################################################################
# Copyright 2014-present trivago GmbH
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################################################################


if test -z $JCHA_CP; then
	JCHA_CP=`dirname "$0"`/target/jcha-1.0-SNAPSHOT.jar
fi

# -- JavaFX is not in the standard runtime path for Java 7 => add it  
JCHA_CP=${JCHA_CP}:${JAVA_HOME}/jre/lib/jfxrt.jar

java -cp ${JCHA_CP} com/trivago/jcha/apps.App $*

