#!/bin/sh

# ---------------------------------------------------------------------------
# jcha - Java Class Histogram Analyser
#        start script
# ---------------------------------------------------------------------------

if test -z $JCHA_CP; then
	JCHA_CP=`dirname "$0"`/target/jcha-1.0-SNAPSHOT.jar
fi

java -cp ${JCHA_CP} com/trivago/jcha/JavaClassHistogramAnalyzer

